#ifndef GITLMVCCONST_H
#define GITLMVCCONST_H
#define GITL_EXE_COMMAND_REQUEST_EVENT "__GITL_EXE_COMMAND_REQUEST__"
#define GITL_UPDATE_UI_REQUEST_EVENT   "__GITL_UPDATE_UI_REQUEST__"
#endif // GITLMVCCONST_H
